spring:
  application:
    name: feature-toggle-audit
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: feature-toggle-audit
  data:
    mongodb:
      uri: mongodb://localhost:27017/feature-toggle-audit

server:
  port: 8083