package com.configly.audit.domain;

public enum AuditType {
    FEATURE_TOGGLE_CREATED,
    FEATURE_TOGGLE_UPDATED,
    FEATURE_TOGGLE_STATUS_CHANGED,
    FEATURE_TOGGLE_VALUE_CHANGED,
    ENVIRONMENT_CREATED,
    ENVIRONMENT_UPDATED,
    ENVIRONMENT_STATUS_CHANGED,
    ENVIRONMENT_TYPE_CHANGED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_STATUS_CHANGED,
}
